fix(d.ts): enable angular2 compilation with TS flag --strictNullChecks
Currently, compiling an ng2 project with TS 1.9 strict null checking causes the following compilation error:

node_modules/@angular/core/src/util/decorators.d.ts(9,5): error TS2411: Property 'extends' of type 'Type | undefined' is not assignable to string index type 'Type | Function | any[]'.

The change to the d.ts file in this pull request eliminates this compilation error.

Fixes: https://github.com/angular/angular/issues/8720